### ISSUE TITLE
Switch between light and dark theme according to the system theme

### ISSUE THREAD

**Issue by Sanqui** [catppuccin/home-assistant#21]
The default Home Assistant theme can switch between light and dark automatically according to the system theme (at least on Firefox on Linux).  It would be awesome if Catppuccin similarly supported switching between the Latte theme and one of the dark themes (doesn't matter which one to me).

**Comment by sedax90** [comment]
You can create a simple automation:

```
alias: Imposta tema predefinito all'avvio
description: ""
triggers:
  - trigger: homeassistant
    event: start
conditions: []
actions:
  - action: frontend.set_theme
    metadata: {}
    data:
      mode: light
      name: Catppuccin Latte
  - action: frontend.set_theme
    metadata: {}
    data:
      name: Catppuccin Mocha
      mode: dark
mode: single
```

**Comment by Crocmagnon** [comment]
It would be easier if there were variants of the themes with Latte as the light mode and Frappe/Macchiato/Moccha as dark mode.
Similar to https://github.com/catppuccin/home-assistant/issues/12

**Comment by uncenter** [comment]
Does #25 fix this?

**Comment by Sanqui** [comment]
I think it would, thank you!

**Comment by uncenter** [comment]
> I think it would, thank you!

Would you be able to test it out? You can download the theme files from the branch on my fork: https://github.com/uncenter/ctp-home-assistant/tree/feat/light-dark-modes.

**Comment by Sanqui** [comment]
I have downloaded https://raw.githubusercontent.com/uncenter/ctp-home-assistant/refs/heads/feat/light-dark-modes/themes/catppuccin.yaml into `/root/config/themes/catppuccin.yaml`, rebooted Home Assistant and set the theme of my dashboard.

The way it works now, if I set _Catppuccin Latte_, and my system theme is light, the theme used is _Latte_, while if my system theme is dark, I see the default _Home Assistant_ theme.  The inverse applies for _Catppuccin_'s dark themes: if my system theme is dark, I see the _Catppuccin_ theme, while if my system theme is light, I see the default _Home Assistant_ theme.  This is an **improvement** over how it was before, since the user's preferred lightness is respected.  Ideally, there would be a way to have both the light and dark variants be _Catppuccin_, though.

Thank you for your work!

**Comment by frittsy** [comment]
This is possible if you combine 2 of the Catppuccin themes under different `modes`, i.e.:
```yaml
Catppuccin:
  modes:
    light:
      # Latte settings here
    dark:
      # Frappe settings here
```
Then quick reload HA and select the Catppuccin theme. You'll now have 3 options for mode (Auto, Light, Dark), just like the default HA theme. Auto will use the system setting.
